# Generated by Django 5.2.2 on 2025-06-06 14:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_link_projectpage_external_link_projectpagetag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='content',
            field=wagtail.fields.StreamField([('block', 3)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('image', 'Image')]}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ul', 'ol', 'link'], 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('type', 0), ('text', 1), ('image', 2)]], {})}),
        ),
    ]
