# Generated by Django 5.2.2 on 2025-06-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectpage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='description',
            new_name='approach',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='content',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='problem',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpage',
            name='subtitle',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
